name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: rony219  
          outputs: dist/github-snake.svg

      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/github-snake.svg
